// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hfnygcphfbjaojtrwcfd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhmbnlnY3BoZmJqYW9qdHJ3Y2ZkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUwMDg3MTIsImV4cCI6MjA3MDU4NDcxMn0.86S1fB3qp7HuePT0u1aSu2YtTcbKftW-x6ATDLYGWx0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});